#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/sampleRegion/polyMesh
rm -f 0/p_rgh.gz

# ----------------------------------------------------------------- end-of-file
