#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication blockMesh
rm -f log.blockMesh

runApplication topoSet
rm -f log.topoSet

runApplication extrudeToRegionMesh -overwrite
rm -f log.extrudeToRegionMesh

cp 0/ph_rgh-orig 0/ph_rgh

# ----------------------------------------------------------------- end-of-file
